### ISSUE TITLE
content 's parent floder?

### ISSUE THREAD

**Issue by JiangLongLiu** [LitileXueZha/MDN-Docs-Desktop#1]
hello where should i put translated-content and content folder

**Comment by LitileXueZha** [comment]
任意位置都行，只要最后**设置好路径**就行了。例如，把这两仓库克隆到你的下载目录：

```
~/Downloads/mdn
├─ content
├─ translated-content
│
```

下载完成后，设置里选择这 2 个目录就行了。（你放桌面或者其它地方都行）

**Comment by JiangLongLiu** [comment]
> 任意位置都行，只要最后**设置好路径**就行了。例如，把这两仓库克隆到你的下载目录：
> 
> ```
> ~/Downloads/mdn
> ├─ content
> ├─ translated-content
> │
> ```
> 
> 下载完成后，设置里选择这 2 个目录就行了。（你放桌面或者其它地方都行）

好的，弄好了，很好用，我之前下载错 electron版本了。
